# Possibly still not the right home...
devel:
  appSrcURL: https://github.com/hybrid-cloud-patterns/spring-petclinic
  appCfgURL: https://github.com/hybrid-cloud-patterns/spring-petclinic-config
  gatlingApp: https://github.com/hybrid-cloud-patterns/spring-petclinic-gatling
  
  image: chat-client:latest
  npmbase: quay.io/hybridcloudpatterns/ubi-npm
  namespace: devsecops-ci
  roxCTLImage: registry.access.redhat.com/advanced-cluster-security/rhacs-roxctl-rhel8:3.71.0-5

global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic
  
  cicd:
    namespace: devsecops-ci

clusterGroup:
  name: development
  isHubCluster: false
  clusterName: wh-dev

  namespaces:
    - stackrox
    - policies
    - openshift-pipelines
    - devsecops-ci
#Adding jchraibi #advanced-devsecops to pattern framework
    - devsecops-dev
    - devsecops-qa

  subscriptions:
  - name: rhacs-operator  #packageName
    namespace: openshift-operators # operator namespace
    channel: rhacs-3.71

  - name: openshift-pipelines-operator-rh
    namespace: openshift-operators
    channel: pipelines-1.7

  - name: quay-bridge-operator
    namespace: openshift-operators
    channel: stable-3.7

  projects:
    - secured
    - ci
    - test-app
#Adding jchraibi #advanced-devsecops to pattern framework
    - spring-petclinic

  applications:
  - name: acs-secured
    namespace: stackrox
    project: secured
    path: charts/hub/acs/secured

  - name: pipelines
    namespace: devsecops-ci
    project: ci
    path: charts/region/pipelines
    ignoreDifferences:
    - kind: ServiceAccount
      jsonPointers:
      - /imagePullSecrets
      - /secrets

  - name: quay-integration
    namespace: openshift-operators
    project: secured
    path: charts/region/quay

  - name: acs-integration
    namespace: stackrox
    project: ci
    path: charts/region/acs

  - name: nexus
    namespace: 
    project: cicd
    path: charts/region/mcdso-tools/nexus

  - name: reports-repo
    namespace: 
    project: cicd
    path: charts/region/mcdso-tools/reports

  - name: sonarqube
    namespace: 
    project: cicd
    path: charts/region/mcdso-tools/sonarqube

#Adding jchraibi #advanced-devsecops to pattern framework
  - name: staging-spring-petclinic
    namespace: devsecops-qa
    project: spring-petclinic
    path: charts/region/stage/spring-petclinic-config

#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#  - name: pipelines
#    namespace: production
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: stable
#    overrides:
#    - name: myparam
#      value: myparam
#
#  - name: pipelines
#    namespace: staging
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: main
