global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

clusterGroup:
  name: prod
  isHubCluster: false
  clusterName: wh-secured

  namespaces:
    - app
    - rhacs-operator
    - stackrox
    - policies

  subscriptions:
  - name: rhacs-operator  #packageName
    namespace: openshift-operators # operator namespace
    channel: rhacs-3.68
    csv: rhacs-operator.v3.68.1

  - name: quay-bridge-operator
    namespace: openshift-operators
    channel: stable-3.6
    csv: quay-bridge-operator.v3.6.6

  projects:
    - app
    - secured

  applications:
  - name: application
    namespace: app
    project: app
    path: charts/all/config-demo

  - name: acs-secured
    namespace: stackrox
    project: secured
    path: common/acs/secured

  - name: quay-integration
    namespace: openshift-operators
    project: secured
    path: charts/region/quay
