---
global:
  pattern: multicluster-devsecops

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  hub:
    region: us-west-2
    clustername: wh-hub
    domain: blueprints.rhecoeng.com

  secure-registry:
    namespace: "openshift-storage"

    s3:
      # Values for S3 bucket access
      # Replace <region> with AWS region where S3 bucket was created
      # Replace <cluster-name> and <domain> with your OpenShift cluster values
      # bucketSource: "https://s3.<region>.amazonaws.com/com.redhat.claudiol.xray-source"
      bucketSource: "https://s3.us-west-2.amazonaws.com/com.redhat.ipbabble.wh-my-bucket" 
      # Bucket base name used for xray images
      bucketBaseName: "wh-my-bucket"

  imageregistry:
    account: ipbabble
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: ipbabble
    username: ipbabble
    email: SOMEWHERE@EXAMPLE.COM
    dev_revision: main

main:
  clusterGroupName: hub
