---
global:
  pattern: multicluster-devsecops

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  secure-registry:
    namespace: "openshift-storage"

    s3:
      # Values for S3 bucket access
      # Replace <region> with AWS region where S3 bucket was created
      # Replace <cluster-name> and <domain> with your OpenShift cluster values
      # bucketSource: "https://s3.<region>.amazonaws.com/com.redhat.myusername.mybucketname"
      bucketSource: "https://s3.us-west-2.amazonaws.com/com.redhat.ipbabble.wh-my-bucket" 
      # Bucket base name used for xray images
      bucketBaseName: "wh-my-bucket"

  imageregistry:
    account: PLAINTEXT
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: PLAINTEXT
    username: PLAINTEXT
    email: SOMEWHERE@EXAMPLE.COM
    dev_revision: main

  quay:
    account: quayadmin
    password: quayadmin123 

devel:
  appURL: https://github.com/ipbabble/chat-client.git
  image: quay-registry-quay-quay-enterprise.apps.wh-hub.blueprints.rhecoeng.com/chat-client:latest
  npmbase: quay.io/hybridcloudpatterns/ubi-npm
  namespace: devsecops-ci
  roxCTLImage: registry.redhat.io/rh-acs/roxctl:3.0.62.0
  quayorg: develorg
  quayorgemail: devel@myorg.com
  quayuser: developer1
  quayuseremail: developer1@myorg.com

main:
  clusterGroupName: hub
  opp: false
