global:
  pattern: common
  valuesDirectoryURL: https://github.com/pattern-clone/common/raw/main
  localClusterName: AUTOMATIC
  options:
    useCSV: True
    syncPolicy: Automatic
    installPlanApproval: Automatic

clusterGroup:
  name: example
  isHubCluster: true