apiVersion: v1
kind: ConfigMap
metadata:
  name: environment
data:
  DESCRIPTION: "Config keys for openshift-pipelines"
#  IMAGE_PROVIDER: {{ .Values.global.imageregistry.hostname }}
#  IMAGE_ACCOUNT: {{ .Values.global.imageregistry.account }}
#  GIT_EMAIL: {{ .Values.global.git.email }}
#  GIT_DEV_REPO_REVISION: {{ .Values.global.git.dev_revision }}
#  GIT_OPS_REPO_TEST_URL: {{ .Values.global.repoURL }}
#  GIT_OPS_REPO_TEST_REVISION: {{ .Values.global.targetRevision }}
#  GIT_OPS_REPO_PROD_URL: {{ .Values.global.repoURL }}
#  GIT_OPS_REPO_PROD_REVISION: {{ .Values.global.targetRevision }}
