apiVersion: quay.redhat.com/v1
kind: QuayIntegration
metadata:
 name: quay
spec:
 clusterID: openshift
 credentialsSecret:
   name: quay-integration
   namespace: openshift-operators
 insecureRegistry: false
 quayHostname: https://quay-registry-quay-quay-enterprise.apps.wh-hub.blueprints.rhecoeng.com