apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
  {{- include "nexus.labels" . | nindent 4 }}
  name: {{ .Values.persistentVolumeClaim.name }}
spec:
  accessModes:
  - {{ .Values.persistentVolumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.resources.requests.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "nexus.labels"  . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nexus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nexus.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}
        env:
        - name: CONTEXT_PATH
          value: /
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containers.port.containerPort }}
          protocol: {{ .Values.containers.port.protocol }}
        livenessProbe:
          exec:
            command:
            - echo
            - ok
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: {{ .Values.containers.readinessProbe.path }}
            port: {{ .Values.containers.readinessProbe.port }}
            scheme: {{ .Values.containers.readinessProbe.scheme }}
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu}}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /{{ .Values.volume.name }}
          name: {{ .Values.volume.name }}
      volumes:
      - name: {{ .Values.volume.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaim.name }}
