---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
  {{- include "nexus.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}
spec:
  port:
    targetPort: {{ .Values.service.ports.name }}
  to:
    kind: {{ .Values.routeTo.kind }}
    name: {{ .Values.routeTo.name }}
    weight: {{ .Values.routeTo.weight }}
