---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
  {{- include "nexus.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}
spec:
  port:
    targetPort: {{ .Values.service.portName }}
  to:
    kind: {{ .Values.route.kind }}
    name: {{ .Values.route.name }}
    weight: {{ .Values.route.weight }}
