# Default values for reports.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/hybridcloudpatterns/nexus3:3.16.2
  pullPolicy: IfNotPresent

containers:
  - name: uploader
    image: quay.io/chmouel/go-simple-uploader:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - path: /fileuploads
        name: staticfiles
    env:
      - name: UPLOADER_PORT
        value: "9000"
      - name: UPLOADER_DIRECTORY
        value: "/fileuploads"
  - name: nginx
    image: quay.io/siamaksade/nginx:latest
    imagePullPolicy: IfNotPresent
    port: 8080
    protocol: TCP
    volumeMounts:
      - path: /etc/nginx/nginx.conf
        name: nginx-conf
      - path: /fileuploads
        name: staticfiles

volumes:
  - container: uploader
    vol:
    - name: nexus-data
      persistentVolumeClaim:
        name: nexus-pv
  - container: nginx
    vol:
    - name: staticfiles
      persistentVolumeClaim:
        name: reports-repo-pv
    - name: nginx-conf
      configMap:
        name: reports-repo-nginx-conf
        mode: 420
  
port:
  containerPort: 8080
  protocol: TCP
readinessProbe:
  path: /
  port: 8080
  scheme: HTTP

service:
  ports:
    name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP

routeTo:
  kind: Service
  name: reports-repo
  weight: 100