apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
  name: create-cosign-pubkey
  namespace: openshift-pipelines
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          export COSIGN_PASSWORD=$(openssl rand -base64 32) 
          cosign key-generate 
          oc wait --for=condition=Available=true deploymentconfig/xraylabdb -n {{ .Values.global.xraylab.namespace }} --timeout=900s
        name: wait-for-xraylab-database
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: pipeline
      serviceAccountName: pipeline
      terminationGracePeriodSeconds: 60