apiVersion: v1
kind: ConfigMap
metadata:
  # quaye abbrev. for Quay Enterprise
  name: create-quaye-pull-secret
  namespace: {{ .Values.quay.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  create-quaye-pull-secret.sh: |
      #!/bin/bash -ex

      function quay_cmd() {
          DATA='{}'
          if [ ! -z "$3" ]; then
              DATA=$3
          fi
          curl -X $1 $CURL_OPTS -H 'Content-Type: application/json'  -H "Authorization: Bearer $TOKEN" $QUAY_HOST$2 --data "$DATA"
      }

      CURL_OPTS="-fSk"

      env | grep QUAY
      if [ -z "$QUAY_HOST" ]; then
          QUAY_HOST="https://quay-registry-quay-quay-enterprise.{{ .Values.global.hubClusterDomain }}"
      fi
      if [ -z "$QUAY_USER" ]; then
          QUAY_USER={{ .Values.quay.setup.user.name }}
      fi
      if [ -z "$QUAY_USER_EMAIL" ]; then
          QUAY_USER_EMAIL={{ .Values.quay.setup.user.email }}
      fi
      if [ -z "$QUAY_ORG" ]; then
          QUAY_ORG={{ .Values.quay.setup.org.name }}
      fi
      if [ -z "$QUAY_ORG_EMAIL" ]; then
          QUAY_ORG_EMAIL={{ .Values.quay.setup.org.email }}
      fi
      if [ -z "$QUAY_REPO" ]; then
          QUAY_REPO={{ .Values.quay.setup.repo }}
      fi

      #  '-n quay-enterprise' is implied
      echo "[INFO] Looking for initial token ..."
      SECRET_NAME=quay-init-token
      COUNT=$(oc get --ignore-not-found=true secret $SECRET_NAME | wc -l) 
      if [ $COUNT = 0 ]; then
          echo "[INFO] Creating default user..."

          INITPASS=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 20 ; echo ''  )

          echo "[INFO] Destroy any previous secrets ..."
          oc delete --ignore-not-found=true secret -n quay-enterprise quay-user
          oc delete --ignore-not-found=true secret -n openshift-operators quay-pull-secret  

          # Invoke API and add quay user to the API - initiates API
          JSONTOKEN=$(curl -X POST -k  $QUAY_HOST/api/v1/user/initialize --header 'Content-Type: application/json' --data "{ \"username\": \"{{ .Values.quay.setup.admin.name }}\", \"password\":\"$INITPASS\", \"email\": \"{{ .Values.quay.setup.admin.email }}\", \"access_token\": true}")

          oc create secret generic $SECRET_NAME --from-literal=token=$JSONTOKEN --from-literal=password=$INITPASS
          echo "quay-init-token created"
      fi
      
      TOKEN=$(oc extract secret/$SECRET_NAME --keys=token --to=- | grep access_token | cut -d : -f2 | awk -F\" '{print $2}')

      # Now extract the token and store in the Quay Integration secret in openshift-operators namespace
      # oc create secret -n openshift-operators generic quay-integration --from-literal=token=$TOKEN

      echo "[INFO] Checking our bearer token is still valid ..."
      COUNT=$(quay_cmd GET /api/v1/superuser/users/ | grep \"$QUAY_USER\" | wc -l)
      if [ $COUNT = 0 ]; then    
          COUNT=$(oc get --ignore-not-found=true secret quay-user | wc -l) 
          if [ $COUNT -gt 1 ]; then
              BASIC=$(oc extract secret/quay-user --keys=basic --to=-)
          
              # This call can be used without a token to show that quay is configured
              COUNT=$(curl -X GET $CURL_OPTS -H 'Content-Type: application/json' -H "Authorization: Basic $BASIC" $QUAY_HOST/api/v1/organization/$QUAY_ORG | wc -l)
              if [ $COUNT -gt 0 ]; then
                  echo "Bearer token has expired"
                  exit 0
              fi
          fi
      fi      

      echo "[INFO] Looking for initial organization ..."
      COUNT=$(quay_cmd GET /api/v1/organization/$QUAY_ORG | grep -v not_found | wc -l)
      if [ $COUNT = 0 ]; then
        echo "[INFO] Creating..."
        # Email cannot be shared with the initial user
        quay_cmd POST /api/v1/organization/  "{\"name\": \"$QUAY_ORG\", \"email\": \"$QUAY_ORG_EMAIL\" }"
      fi
      
      echo "[INFO] Looking for org application ..."
      # The only way to get another OAuth token is to go to: Organization -> Applications -> {app} -> Generate Token 
      APPLICATION=automation
      COUNT=$(quay_cmd GET /api/v1/organization/$QUAY_ORG/applications | grep $APPLICATION | wc -l)
      if [ $COUNT = 0 ]; then
        echo "[INFO] Creating..."
        quay_cmd POST /api/v1/organization/$QUAY_ORG/applications "{\"name\": \"$QUAY_ORG-automation\", \"description\": \"automation app\" }"
      fi

      echo "[INFO] Looking for our superuser ..."
      COUNT=$(quay_cmd GET /api/v1/superuser/users/ | grep \"$QUAY_USER\" | wc -l)
      if [ $COUNT = 0 ]; then    
          echo "[INFO] Creating..."
          RESPONSE=$(quay_cmd POST /api/v1/superuser/users/ "{ \"username\": \"$QUAY_USER\", \"email\": \"$QUAY_USER_EMAIL\", \"access_token\": true}")

          QUAY_PASSWORD=$(echo $RESPONSE | cut -d : -f5 | awk -F\} '{print $1}')
          BASE64AUTH=`echo $QUAY_USER:$QUAY_PASSWORD | base64 -w0`

          echo "[INFO] Creating a secret with user/password ..."
          oc create secret -n quay-enterprise generic quay-user --from-literal=token="$RESPONSE" --from-literal=basic="$BASE64AUTH"

          echo -e "{ \"auths\": { \"$QUAY_HOST\": { \"auth\": \"$BASE64AUTH\" } }}" | oc create secret generic --namespace=openshift-operators quay-pull-secret --from-file=.dockerconfigjson=/dev/stdin --type=kubernetes.io/dockerconfigjson

          BASIC=$(oc extract secret/quay-user --keys=basic --to=-)
          curl -X GET $CURL_OPTS --header 'Content-Type: application/json' -H "Authorization: Basic $BASIC" $QUAY_HOST/api/v1/organization/$QUAY_ORG
          
          # https://access.redhat.com/solutions/5462311
          # Requires CLIENTID to be added to DIRECT_OAUTH_CLIENTID_WHITELIST for this to work
          # If it worked, we could create a new OAuth token when the original one expires after 150min
          ####
          # CLIENTID=$(quay_cmd GET /api/v1/organization/$QUAY_ORG/applications | sed -e 's/{/\n/g' | grep "\"name\": \"$APPLICATION\"" | sed -e 's/,/\n/g' | grep client_id | awk '{print $2}' | sed 's/"//g')
          # quay_cmd PUT $CURL_OPTS --header 'Content-Type: application/json' -H "Authorization: Basic $BASE64AUTH" $QUAY_HOST/oauth/authorize?response_type=token&client_id=$CLIENTID&scope=org:admin%20repo:admin%20repo:create%20repo:read%20repo:write%20super:user%20user:admin%20user:read&redirect_uri=$QUAY_HOST%2Foauth%2Flocalapp
      fi

      echo "[INFO] Looking for initial repo ..."
      COUNT=$(quay_cmd GET /api/v1/repository/$QUAY_ORG/$QUAY_REPO | grep -v not_found | wc -l)
      if [ $COUNT = 0 ]; then
          echo "[INFO] Creating..."
          quay_cmd POST /api/v1/repository "{\"namespace\":\"$QUAY_ORG\", \"repository\":\"$QUAY_REPO\", \"visibility\":\"public\", \"description\":\"Development Repo\", \"repo_kind\":\"image\"}"  
      fi

      COUNT=$(quay_cmd GET /api/v1/organization/$QUAY_ORG/team/owners/members | grep "name\": \"$QUAY_USER\"" | wc -l)
      if [ $COUNT = 0 ]; then
          echo "[INFO] Associating $QUAY_USER with $QUAY_ORG"
          quay_cmd PUT /api/v1/organization/$QUAY_ORG/team/owners/members/$QUAY_USER '{}'
      fi

      COUNT=$(quay_cmd GET /api/v1/repository/$QUAY_ORG/$QUAY_REPO/permissions/user/$QUAY_USER | grep '"role": "admin"' | wc -l)
      if [ $COUNT = 0 ]; then
          echo "[INFO] Give $QUAY_USER admin rights to the repo"
          quay_cmd PUT /api/v1/repository/$QUAY_ORG/$QUAY_REPO/permissions/user/$QUAY_USER '{ "role": "admin"}'
      fi


      echo "[INFO] Job finished"
