apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "7"
  name: enable-quay-api
  namespace: {{ .Values.quay.namespace }}
spec:
  template:
    spec:
      containers: 
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          TOKEN=$(curl -X POST -k  https://quay-registry-quay-quay-enterprise.apps.{{ .Values.global.hub.clustername }}.{{ .Values.global.hub.domain }}/api/v1/user/initialize --header 'Content-Type: application/json' --data '{ "username": "{{ .Values.global.quay.account }}", "password":"{{ .Values.global.quay.password }}", "email": "{{ .Values.global.quay.email }}", "access_token": true}')
          echo ${TOKEN} | grep access_token | cut -d : -f2 | awk -F\" '{print $2}'
          oc create secret generic quaytoken --from-literal=token=$(TOKEN=$(oc extract secret/quaytoken --keys=token --to=- | grep access_token | cut -d : -f2 | awk -F\" '{print $2}'))
          echo $TOKEN
        name: quay-api-enablement
      dnsPolicy: ClusterFirst
      activeDeadlineSeconds: 900
      restartPolicy: Never
      serviceAccountName: quay-admin-sa
      terminationGracePeriodSeconds: 60