apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "6"
  name: wait-for-quay-app-deploy
  namespace: {{ .Values.quay.namespace }}
spec:
  template:
    spec:
      containers: 
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          #oc wait --for=condition=available deploy/quay-registry-quay-app -n {{ .Values.quay.namespace }} --timeout=300s 
          # Don't need this sleep but might as well give some time before we wait on the availability
          sleep 30
          # wait for the operator QuayRegistry CR
          oc wait QuayRegistry quay-registry --for=condition=Available=true
        name: wait-for-quay-app
      dnsPolicy: ClusterFirst
      activeDeadlineSeconds: 900
      restartPolicy: Never
      serviceAccountName: quay-admin-sa
      terminationGracePeriodSeconds: 60