apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
  name: wait-for-noobaa-deployment
  namespace: quay-enterprise
spec:
  template:
    spec:
      containers: 
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          # We need to wait on noobaa and we know it takes about 30 seconds
          sleep 30 
          oc wait --for=condition=available deploy/noobaa-endpoint -n openshift-storage --timeout=900s
        name: noobaa-deployment-pause
      dnsPolicy: ClusterFirst
      activeDeadlineSeconds: 900
      restartPolicy: Never
      serviceAccountName: quay-admin-sa
      terminationGracePeriodSeconds: 60