apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: label-storage-nodes-bundle
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash
              set -e
              if ! oc get nodes -l cluster.ocs.openshift.io/openshift-storage= ; then
                 echo "Worker nodes already labeled for storage"
                exit 0
              else
                # Wait for central to be ready
                attempt_counter=0
                max_attempts=20
                echo "Labeling all worker nodes for storage"
                oc label node -l node-role.kubernetes.io/worker= cluster.ocs.openshift.io/openshift-storage=
                echo "Worker nodes labeled for storage"
              fi
          imagePullPolicy: Always
          name: label-storage-nodes-bundle
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.clusterGroup.name }}-gitops-argocd-application-controller
      serviceAccountName: {{ .Values.clusterGroup.name }}-gitops-argocd-application-controller
      terminationGracePeriodSeconds: 30