apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: label-storage-nodes
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash
              if oc get nodes -l cluster.ocs.openshift.io/openshift-storage= &> /dev/null; then
                echo "Worker nodes already labeld for storage"
                exit 0
              else

                # Wait for central to be ready
                attempt_counter=0
                max_attempts=20
                echo "Labeling all worker nodes for storage"
                oc label node -l node-role.kubernetes.io/worker= cluster.ocs.openshift.io/openshift-storage= &> /dev/null

                echo "Worker nodes labeled for storage"
              fi
          imagePullPolicy: Always
          name: create-cluster-init-bundle
      dnsPolicy: ClusterFirst
      restartPolicy: Never
#      serviceAccount: label-storage-nodes
#      serviceAccountName: label-storage-nodes
      terminationGracePeriodSeconds: 30