apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  name: quay-admin-role
rules:
  - apiGroups:
      - "apps"
    resources:
      - deployment
    verbs:
      - get
      - create
      - list
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - list

