apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: quay-admin-role
rules:
  - apiGroups:
      - "apps/v1"
    resources:
      - deployment
    verbs:
      - get
      - list
      - patch
      - update
