apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  name: quay-admin-role
rules:
  - apiGroups:
      - "apps/v1"
      - "v1"
      - "route.openshift.io/v1"
    resources:
      - deployment
      - secrets
      - routes
    verbs:
      - get
      - create
      - list
      - patch
      - update
