apiVersion: v1
kind: ConfigMap
metadata:
  name: chains-config
  namespace: openshift-pipelines
data:
  artifacts.oci.storage: ''
  artifacts.taskrun.format: tekton
  artifacts.taskrun.storage: tekton