quay:
  namespace: quay-enterprise
  component:
    - name: clair
      managed: true
    - name: horizontalpodautoscaler
      managed: true
    - name: mirror
      managed: true
    - name: monitoring
      managed: true
    - name: postgres  
      managed: true 
    - name: redis 
      managed: true 
    - name: objectstorage 
      managed: true 
    - name: route 
      managed: true 
    - name: tls 
      managed: true
    - name: quay
      managed: true
    - name: clairpostgres
      managed: true
  configBundleSecret:
    deploy: true
    name: quay-init-config-bundle-secret
  setup:
    admin:
      name: quay
      # Password SHOULD NOT be here!
      password: quayadmin123
      email: quayadmin@example.com
    org:
      name: devel
      email: devel@myorg.com
    user:
      name: admin
      email: admin@myorg.com
    repo: example

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest

global:
  hub:
    clustername: NAME
    domain: DOMAIN

  quay:
