quay:
  namespace: quay-enterprise
  adminuser: quayadmin
  component:
    - name: clair
      managed: true
    - name: horizontalpodautoscaler
      managed: true
    - name: mirror
      managed: true
    - name: monitoring
      managed: true
    - kind: postgres  
      managed: true 
    - kind: redis 
      managed: true 
    - kind: objectstorage 
      managed: true 
    - kind: route 
      managed: true 
    - kind: tls 
      managed: true
  configBundleSecret:
    deploy: false
    name: quay-init-config-bundle-secret
