apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: secured-cluster-secret-policy
  namespace: stackrox
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: SkipPrune
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: secured-cluster-secret
          annotations:
            apps.open-cluster-management.io/deployables: "secret"
            policy.open-cluster-management.io/trigger-update: "2"
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
              - rhacs-operator
              - stackrox
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                data:
                  # admission-control-cert.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "admission-control-tls").data "admission-control-cert.pem" hub}}` }}'
                  # admission-control-key.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "admission-control-tls").data "admission-control-key.pem" hub}}` }}'
                  # ca.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "admission-control-tls").data "ca.pem" hub}}` }}'
                  admission-control-cert.pem: '{{ `{{hub fromSecret "stackrox" "admission-control-tls" "admission-control-cert.pem" hub}}` }}'
                  admission-control-key.pem: '{{ `{{hub fromSecret "stackrox" "admission-control-tls" "admission-control-key.pem" hub}}` }}'
                  ca.pem: '{{ `{{hub fromSecret "stackrox" "admission-control-tls" "ca.pem" hub}}` }}'
                kind: Secret
                metadata:
                  name: admission-control-tls
                  namespace: stackrox
                type: Opaque
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                data:
                  # sensor-cert.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").data "sensor-cert.pem" hub}}` }}'
                  # sensor-key.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").data "sensor-key.pem" hub}}` }}'
                  # ca.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").data "ca.pem" hub}}` }}'
                  sensor-cert.pem: '{{ `{{hub fromSecret "stackrox" "sensor-tls" "sensor-cert.pem" hub}}` }}'
                  sensor-key.pem: '{{ `{{hub fromSecret "stackrox" "sensor-tls" "sensor-key.pem" hub}}` }}'
                  ca.pem: '{{ `{{hub fromSecret "stackrox" "sensor-tls" "ca.pem" hub}}` }}'
                  acs-host: '{{ `{{hub fromSecret "stackrox" "sensor-tls" "acs-host" hub}}` }}'
                kind: Secret
                metadata:
                  name: sensor-tls
                  namespace: stackrox
                type: Opaque
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                data:
                  # collector-cert.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").data "collector-cert.pem" hub}}` }}'
                  # collector-key.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").data "collector-key.pem" hub}}` }}'
                  #  ca.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").data "ca.pem" hub}}` }}'
                  collector-cert.pem: '{{ `{{hub fromSecret "stackrox" "collector-tls" "collector-cert.pem" hub}}` }}'
                  collector-key.pem: '{{ `{{hub fromSecret "stackrox" "collector-tls" "collector-key.pem" hub}}` }}'
                  ca.pem: '{{ `{{hub fromSecret "stackrox" "collector-tls" "ca.pem" hub}}` }}'
                kind: Secret
                metadata:
                  name: collector-tls
                  namespace: stackrox
                type: Opaque
