---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: git-secret
  namespace: devsecops-ci
spec:
  refreshInterval: 15s
  target:
    name: git-secret
    template:
      type: Opaque
  dataFrom:
  - extract: 
      key: {{ .Values.configdemosecret.key }}