# The policy needs to be added to the ACM HUB and then it will be pushed on all clusters
# except the HUB (see placementrule on the bottom)
{{ if .Values.clusterGroup.isHubCluster }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-reports-nginx-config
  namespace: devsecops-ci
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: SkipPrune
    argocd.argoproj.io/sync-wave: "15"
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: reports-nginx-configmap-policy
          annotations:
            apps.open-cluster-management.io/deployables: "configmap"
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            include:
              - default
              - devsecops-ci
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: ConfigMap
                metadata:
                  name: reports-repo-nginx-conf
                  namespace: devsecops-ci
                data:
                  htpasswd: |
                    reports: '{{ `{{hub fromSecret "devsecops-ci" "reports-nginx-htpasswd" "reports" hub}}` }}'
                  nginx.conf: "types {\n    text/plain    yaml yml;\n}\n\nserver {\n    listen 8080
                    default_server;\n    gzip on;\n\n\tlocation /upload {\n\t\tsatisfy any;\n\t\tauth_basic
                      \"Welcome to the Jungle!\"; #For Basic Auth\n    \tauth_basic_user_file conf.d/htpasswd;
                      \ #For Basic Auth\n\t\tdeny all;\n\n\t\tproxy_set_header  Host $host;\n\t\tproxy_set_header
                      \ X-Real-IP $remote_addr;\n\t\tproxy_set_header  X-Forwarded-Proto https;\n\t\tproxy_set_header
                      \ X-Forwarded-For $remote_addr;\n\t\tproxy_set_header  X-Forwarded-Host $remote_addr;\n\n\t\tproxy_pass
                      http://localhost:9000;\n\t}\n\n\tlocation /private {\n\t\troot /fileuploads;\n\n\t\tsatisfy
                      any;\n\t\tauth_basic \"Welcome to the Jungle!\"; #For Basic Auth\n    \tauth_basic_user_file
                      conf.d/htpasswd;  #For Basic Auth\n\t\tdeny all;\n\n\t    autoindex
                      on;\n\t    autoindex_exact_size off;\n\t    autoindex_localtime on;\n\t}\n\n\tlocation
                      / {\n\t\troot /fileuploads;\n\t    autoindex on;\n\t    autoindex_exact_size off;\n\t
                      \   autoindex_localtime on;\n\t}\n}\n"
                
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: reports-nginx-configmapg-placement-binding
  namespace: devsecops-ci
placementRef:
  name: reports-nginx-configmap-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-reports-nginx-config
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
# We need to run this on any managed cluster but not on the HUB
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: reports-nginx-configmap-placement
  namespace: devsecops-ci
spec:
  # This will go to both devel and secured clusters
  clusterSelector:
    # Using matchExpression because I need it in more than one clusterGroup/cluster-group
    matchExpressions:
      - key: clusterGroup
        operator: In
        values:
          - devel
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
{{ end }}
