kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: skopeo-copy
spec:
  workspaces:
  - name: config
    description: configmap contents
  params:
  - name: TAG
    type: string
  - name: SOURCE_IMAGE
    type: string
  - name: TARGET_IMAGE_CONFIGMAPKEY
    type: string
  steps:
  - name: skopeo-copy
    image: quay.io/hybridcloudpatterns/ubi-npm:latest
    script: |
      skopeo copy --src-tls-verify=false --dest-tls-verify=false quay.io://$(params.SOURCE_IMAGE):$(params.TAG) docker://$(cat $(workspaces.config.path)/IMAGE_PROVIDER)/$(cat $(workspaces.config.path)/IMAGE_ACCOUNT)/$(cat $(workspaces.config.path)/$(params.TARGET_IMAGE_CONFIGMAPKEY)):$(params.TAG)