apiVersion: v1
kind: Pod
metadata:
  name: link-pull-secret
  namespace: devsecops-ci
  annotations:
    # Tekton magic, see https://tekton.dev/vault/pipelines-v0.15.2/auth/
    tekton.dev/docker-0: https://{{ .Values.global.imageregistry.hostname }}  
spec:
  containers:
    - name: web
      image: quay.io/hybridcloudpatterns/ubi-npm
  imagePullSecrets:
    - name: ipbabble-blueprintbot-pull-secret