apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: stackrox-secured-cluster-services
  namespace: stackrox
spec:
  clusterName: '{{ `{{ fromSecret "open-cluster-management-agent" "hub-kubeconfig-secret" "cluster-name" | base64dec }}` }}'
  auditLogs:
    collection: Auto
  admissionControl:
    listenOnUpdates: true
    bypass: BreakGlassAnnotation
    contactImageScanners: DoNotScanInline
    listenOnCreates: true
    timeoutSeconds: 3
    listenOnEvents: true
  centralEndpoint: central-stackrox.{{ .Values.global.hubClusterDomain }}:443
  # Or use this when we figure out ahy acs-host is empty and fix it
  # {{ fromSecret "stackrox" "sensor-tls" "acs-host" | base64dec }}
  perNode:
    collector:
      collection: KernelModule
      imageFlavor: Regular
    taintToleration: TolerateTaints
