---
apiVersion: v1
kind: Service
metadata:
  labels:
  {{- include "reports.selectorLabels" . | nindent 4 }}
  name: {{ .Chart.Name }}-repo
spec:
  ports:
  - name: {{ .Values.service.portName }}
    port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
  {{- include "reports.selectorLabels" . | nindent 4 }}
