---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}-repo
  name: {{ .Chart.Name }}-repo
spec:
  ports:
  - name: {{ .Values.service.ports.name }}
    port: {{ .Values.service.ports.port }}
    protocol: {{ .Values.service.ports.protocol }}
    targetPort: {{ .Values.service.ports.targetPort }}
  selector:
  {{- include "reports.selectorLabels" . | nindent 4 }}
